LFG.WebUI/Controllers/NavController.cs
using LFG.Domain.Abstract;
using LFG.Domain.Entities;
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace LFG.WebUI.Controllers
{
    public class NavController : Controller
    {
        private IActivityRepository repository;
        public NavController(IActivityRepository repo)
        {
            repository = repo;
        }

        public PartialViewResult TopPanel()
        {
            return PartialView();
        }


        //UnitTest1 - Can_Create_Categories(), Indicates_Selected_Category()
        public PartialViewResult Menu(string category = null)
        {
            ViewBag.SelectedCategory = category;

            IEnumerable<string> result = repository.Activities
                .Select(Activity => Activity.ActivityTypeCurrent.ToString())
                .Distinct()
                .OrderBy(s => s);
            return PartialView(result);
        }
    }
}

LFG.WebUI/Controllers/SubListController.cs
using LFG.Domain.Abstract;
using LFG.Domain.Entities;
using LFG.WebUI.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace LFG.WebUI.Controllers
{
    public class SubListController : Controller
    {
        private IActivityRepository repository;
        public SubListController(IActivityRepository repo)
        {
            repository = repo;
        }

        public RedirectToRouteResult SubActivity(Activity activity, string returnUrl)
        {
            //Activity Activity = repository.Activities
            //    .FirstOrDefault(g => g == activity);

            //if (activity != null)
            //{
            //    GetList().AddItem(activity);
            //}
            return RedirectToAction("Index", new { returnUrl });
        }

        public RedirectToRouteResult RemoveFromCart(int gameId, string returnUrl)
        {
            //Game game = repository.Games
            //    .FirstOrDefault(g => g.GameId == gameId);

            //if (game != null)
            //{
            //    GetList().RemoveLine(game);
            //}
            return RedirectToAction("Index", new { returnUrl });
        }

        public SubList GetList()
        {
            SubList subList = (SubList)Session["Cart"];
            //if (subList == null)
            //{
            //    subList = new SubList();
            //    Session["Cart"] = subList;
            //}
            return subList;
        }
    }
}

LFG.WebUI/Views/Shared/ActivitySummary.cshtml
@model LFG.Domain.Entities.Activity

<div class="well">
    <div>
        <span class="pull-right label label-primary">
            Опубликовано:
            @Model.ActivityPostDayTime.ToString("dddd, dd MMMM в HH:mm", new CultureInfo("ru-RU"))
            @Html.HiddenFor(x => x.ActivityId)
            @Html.Hidden("returnUrl", Request.Url.PathAndQuery)

        </span>
        <br />
        <span class="pull-right ">
            @using (Html.BeginForm("Sub", "Activity", FormMethod.Post, new { id = Model.ActivityId }))
            {
                <button class="btn btn-success" type="submit">
                    Я пойду!
                </button>
            }
        </span>
    </div>
    <h3>
        <strong>@Html.ActionLink(Model.ActivityName, "Page", new { id = Model.ActivityId })</strong>
    </h3>

    <br>
    <span class="lead">@Model.ActivityDescription</span>
    @using (Html.BeginForm("SubActivity", "SubList"))
    {

    }

</div>

LFG.WebUI/Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="~/Content/bootstrap.css" rel="stylesheet" />
    <link href="~/Content/bootstrap-theme.css" rel="stylesheet" />
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
    <script src="//netdna.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
    <link rel="stylesheet" type="text/css" href="//netdna.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <link href="~/Content/ErrorStyles.css" rel="stylesheet" />

    <title></title>
</head>
<body>
    <div class="navbar navbar-inverse" role="navigation">
        @Html.Action("TopPanel", "Nav")
    </div>
    <div>
        @if (TempData["message"] != null)
        {
            <div class="alert alert-success">@TempData["message"]</div>
        }
        @if (TempData["error"] != null)
        {
        <div class="alert alert-danger">@TempData["error"]</div>
        }
        @RenderBody()
    </div>
</body>
</html>

LFG.WebUI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="~/Content/bootstrap.css" rel="stylesheet" />
    <link href="~/Content/bootstrap-theme.css" rel="stylesheet" />
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
    <script src="//netdna.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
    <link rel="stylesheet" type="text/css" href="//netdna.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <title>@ViewBag.Title</title>
</head>
<body>
    <div class="navbar navbar-inverse" role="navigation">
        @Html.Action("TopPanel", "Nav")
    </div>
    <div class="row panel">   
            @RenderBody()
    </div>
</body>
</html>